language: node_js
node_js:
- '12'
cache: yarn
install: yarn
script:
- yarn lint
- npm run test:coverage
after_success:
- yarn report-coverage
- yarn build
notifications:
  slack:
    matrix:
    - hermes-develop:LmsG8kHM3ZYhSVYzmbpMFSNo
    rooms:
      secure: NZ5oHWPQ1kf5gNmK3ocO8+zhdg1VlC7Y+/wKy2dRbIORaJ8MGcHdNOw8PYVzY4yigM/7wyqDyq5GsKzAK3I1o9Spf0tQ00RZDPtJusl6hMs1G+HzH66savjllSlUWl37/z9uBLt8LiOP1egBMiL56PJIc4ofexBqEQMd4XUjVNtiK3ryerPnhGy6da0N3y3ihM9kXsIfHH+9liGMWDf9faKJOVMTAICfR945pfu1FkHkt+QnBpj/AwicSAAzD5mDP5lLMcRmPUzd5uWrjRw05E/BiEe8ttYeptmcRqKLPrDDydBucgQrD78Hc6ei+YfnQ+2xnNW7YJa6d7F2FLD8aaCCpBXDBVyWtFyIZOYvVhn3iXu9cxMQVVTVTXdJTYV5QXt3F4OEaKGydBRTPapeZ6cZohMryafM4/+v0nE5a6fh+gLT1fWx96R3SURwvaiZw5FOfvQ6r9EDzj45RHtaQrJ5J9ogbrbdLurEJWoMfMjwmJuhhA3mX15/M5YkZlZECjyELuOvY/1jNJ0V+lEWodgY6LphpwO/VU7IcqMqinnPLAUQQfFP6U5LduiadNK2sZnSjU+/LAI8dVX1u5Mj8iubVTQiysD2DHdLH3sS9Z8/1OJPx35gMVNc9HT6f8tuP0lJ7lfAvGug+zkgpvImB3FMMJ02UKQxGKiRsnWwp6Q=
deploy:
  provider: npm
  email: mercury.iwork@gmail.com
  api_key:
    secure: Rbodo0JWXSFU7Ei0+OKCY8r7fYeBZGI19N1LRcnODB4i4elCJizOstoJbU6ifBwSI00SA0YWr5mt3vXccTZeqIRPBazMeDQp4IDh3elCtRwRByCNNj2m4FOFxcHIWmTNH4Tjem69YoyDf7jYQJ2Ohyz32PV5lv2bE87Z+xLYSj5qwxza6HOvnEnmJJECfug82lyoxle60wYwc2g4HAFwX8yRUQ+c5MMoYYz8DxcKEbELz5AF091dYBda4J4vGF8nwIi29wB5QCQLBc4q6iHMo0rk+4UnE54j/MwpCe7EEHf9LdE7huvw5WFSXs0278ZIPla0MgkDlbA4FVDWMgWYEFeMkkoYGqB4mEH7JfjfvoY3+Dc5rCijJkPtELI+eJGvJfblqpY+BNsxC4JN1lTMsCTlN76ML8zkfZIf5vYgbhJbP8aQ0I14K6XMyDWoUV6ZQCGDaX+9z9wlXblbMCm/gvenVIZR4qUEgBx5YdIR5n87BZY6iMYjdXqgIPiIt9yctmQmEMvYY9DchP3CLzeBVYKwA+Jx9Qpd/vZlK/hG2ajkmYos/aouy9BWHMLcj5g2f2pJOt1pF7fezIuNB6NRDETuyA6GugR3xJHDfqJwhWnTj8i+MZ8snleCbfsJy8srD5mSFYXjuDSJ1ecHuTJFcjrt3bRL5OuQGwmZxBOK5m0=
  skip_cleanup: true
  on:
    tags: true
    repo: hermeslin/guardian-of-env
